package com.quascenta.petersroad.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {


    private final DaoConfig sensorsDaoConfig;
    private final DaoConfig slogDaoConfig;
    private final DaoConfig unitDaoConfig;
    private final DaoConfig device_logDaoConfig;



    private final sensorsDao sensorsDao;
    private final slogDao slogDao;
    private final unitDao unitDao;
    private final device_logDao device_logDao;


    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);




        sensorsDaoConfig = daoConfigMap.get(sensorsDao.class).clone();
        sensorsDaoConfig.initIdentityScope(type);

        slogDaoConfig = daoConfigMap.get(slogDao.class).clone();
        slogDaoConfig.initIdentityScope(type);

        unitDaoConfig = daoConfigMap.get(unitDao.class).clone();
        unitDaoConfig.initIdentityScope(type);

        device_logDaoConfig = daoConfigMap.get(device_logDao.class).clone();
        device_logDaoConfig.initIdentityScope(type);





        sensorsDao = new sensorsDao(sensorsDaoConfig, this);
        slogDao = new slogDao(slogDaoConfig, this);
        unitDao = new unitDao(unitDaoConfig, this);
        device_logDao = new device_logDao(device_logDaoConfig, this);



        registerDao(sensors.class, sensorsDao);
        registerDao(slog.class, slogDao);
        registerDao(unit.class, unitDao);
        registerDao(device_log.class, device_logDao);

    }
    
    public void clear() {

        sensorsDaoConfig.getIdentityScope().clear();
        slogDaoConfig.getIdentityScope().clear();
        unitDaoConfig.getIdentityScope().clear();
        device_logDaoConfig.getIdentityScope().clear();

    }



    public sensorsDao getSensorsDao() {
        return sensorsDao;
    }

    public slogDao getSlogDao() {
        return slogDao;
    }

    public unitDao getUnitDao() {
        return unitDao;
    }

    public device_logDao getDevice_logDao() {
        return device_logDao;
    }



}
