package com.quascenta.petersroad.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SLOG.
*/
public class slogDao extends AbstractDao<slog, Long> {

    public static final String TABLENAME = "SLOG";

    /**
     * Properties of entity slog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "slog_id");
        public final static Property Sl_time = new Property(1, Long.class, "sl_time", false, "SL_TIME");
        public final static Property Sl_value = new Property(2, Float.class, "sl_value", false, "SL_VALUE");
        public final static Property Sl_active = new Property(3, Boolean.class, "sl_active", false, "SL_ACTIVE");
    };

    private DaoSession daoSession;


    public slogDao(DaoConfig config) {
        super(config);
    }
    
    public slogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SLOG' (" + //
                "'slog_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SL_TIME' INTEGER," + // 1: sl_time
                "'SL_VALUE' REAL," + // 2: sl_value
                "'SL_ACTIVE' INTEGER);"); // 3: sl_active
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SLOG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, slog entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long sl_time = entity.getSl_time();
        if (sl_time != null) {
            stmt.bindLong(2, sl_time);
        }
 
        Float sl_value = entity.getSl_value();
        if (sl_value != null) {
            stmt.bindDouble(3, sl_value);
        }
 
        Boolean sl_active = entity.getSl_active();
        if (sl_active != null) {
            stmt.bindLong(4, sl_active ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(slog entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public slog readEntity(Cursor cursor, int offset) {
        slog entity = new slog( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // sl_time
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // sl_value
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // sl_active
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, slog entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSl_time(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSl_value(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setSl_active(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(slog entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(slog entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUnitDao().getAllColumns());
            builder.append(" FROM SLOG T");
            builder.append(" LEFT JOIN UNIT T0 ON T.'slog_id'=T0.'unit_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected slog loadCurrentDeep(Cursor cursor, boolean lock) {
        slog entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        unit unit = loadCurrentOther(daoSession.getUnitDao(), cursor, offset);
        entity.setUnit(unit);

        return entity;    
    }

    public slog loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<slog> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<slog> list = new ArrayList<slog>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<slog> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<slog> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
